#!/bin/bash

set -x

INSTALL_PATH=/usr/local/createUser
SITEHOME_PATH=/usr/www
SKELETON_PATH=/etc/website_account_skeleton
VSFTPD_PATH=/etc/vsftpd
NGINXSA_PATH=/etc/nginx/sites-available
NGINXSE_PATH=/etc/nginx/sites-enabled
PHPFPM_PATH=/etc/php-fpm
VER=$2

if test "$VER" == "" ; then

	read -p "You did not supply 2nd argument, defaulting to PHP5.3 - Are you sure you want to proceed? " -n 1 -r
	
	if [[ $REPLY =~ ^[Nn]$ ]] ; then
		exit 2
	fi

	VER=php53
fi

if test "$1" == "" ; then
	/bin/echo $'\a'Domain is required, e.g: $0 example.com
	exit 1
fi

if [ -d "$SITEHOME_PATH/$1" ] ; then
        /bin/echo $'\a'Home dir create would fail
        exit 1
fi

/usr/bin/id $1 &> /dev/null

RETVAL=$?

if [ $RETVAL -eq 0 ] ; then
	/bin/echo $'\a'User already exists
	exit 1
fi

/usr/sbin/useradd -b $SITEHOME_PATH -s /sbin/nologin -k $SKELETON_PATH -m $1

RETVAL=$?

if [ $RETVAL -eq 0 ] ; then

	/bin/echo $1 >> $VSFTPD_PATH/user_list
	/bin/echo $1 >> $VSFTPD_PATH/chroot_list

	/bin/sed s/TEMPLATE/$1/ $INSTALL_PATH/nginx-templates/template.conf > $NGINXSA_PATH/$1.conf
	/bin/ln -s $NGINXSA_PATH/$1.conf $NGINXSE_PATH/

	if test "$VER" == "php53" ; then
		/bin/sed s/TEMPLATE/$1/ $INSTALL_PATH/php-fpm-templates/template.53.conf > $PHPFPM_PATH/php.$1.conf
		/bin/sed s/TEMPLATE/$1/ $INSTALL_PATH/init-script-templates/template.53.init > /etc/init.d/php.$1
	fi

	if test "$VER" == "php52" ; then
		/bin/sed s/TEMPLATE/$1/ $INSTALL_PATH/php-fpm-templates/template.52.conf > $PHPFPM_PATH/php.$1.conf
		/bin/sed s/TEMPLATE/$1/ $INSTALL_PATH/init-script-templates/template.52.init > /etc/init.d/php.$1
	fi

	CURRPORT=$(/bin/grep -ho ':9[[:digit:]]*' $PHPFPM_PATH/*.conf | sort | tail -n1 | awk -F: '{print $2}')
	NEXTPORT=$(($CURRPORT + 1))

	/bin/sed -i s/PORT/$NEXTPORT/ $PHPFPM_PATH/php.$1.conf
	/bin/sed -i s/PORT/$NEXTPORT/ $NGINXSA_PATH/$1.conf
	/bin/sed -i s/TEMPLATE/$i/ $SITEHOME_PATH/$1/web/index.html

	/bin/chmod +x /etc/init.d/php.$1
	/bin/chmod og+rx $SITEHOME_PATH/$1

	/sbin/chkconfig php.$1 on
	/sbin/service php.$1 start
	/sbin/service nginx reload

	PASS=$(/usr/bin/mkpasswd $1)	

	/bin/echo $'\a'Added user with password: $PASS
	exit 0
fi

exit 1
